### ISSUE TITLE
ensure community page user verification emails are sent to admin

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#804] opened 2018-05-29 22:23 UTC
we used to receive user signup notification emails at brcaexchange@gmail.com to approve new users. at some point they stopped coming. check with melissa where to have these emails sent to.

**Comment by melissacline** [comment] 2018-07-23 19:18
Duplicate of # 836

**Closed by melissacline** 2018-07-23 19:18 UTC
Labels: ready
